export const GAME_OVER = 'GAME_OVER'
export const QUESTION_NEXT = 'QUESTION_NEXT'
export const ANSWER_SUBMIT = 'ANSWER_SUBMIT'

export const QUESTIONS_LOADING = 'QUESTIONS_LOADING'
export const QUESTIONS_FETCH_ERROR = 'QUESTIONS_FETCH_ERROR'
export const QUESTIONS_FETCH_SUCCESS = 'QUESTIONS_FETCH_SUCCESS'